Login to pincone and create Index

https://www.pinecone.io/

In [ ]:
pip install pinecone

In [ ]:
from pinecone import Pinecone, ServerlessSpec

In [ ]:
documents = [
    {
        "id": "doc-001",
        "text": "Pinecone is a fully managed vector database for search and recommendation.",
        "category": "documentation",
        "tag": "pinecone",
        "difficulty": "beginner",
        "url": "https://example.com/pinecone-intro"
    },
    {
        "id": "doc-002",
        "text": "To use Pinecone with Python, you create an index and upsert vectors with metadata.",
        "category": "documentation",
        "tag": "python",
        "difficulty": "beginner",
        "url": "https://example.com/pinecone-python"
    },
    {
        "id": "doc-003",
        "text": "Vector databases store embeddings that capture semantic meaning for semantic search.",
        "category": "blog",
        "tag": "vector-db",
        "difficulty": "intermediate",
        "url": "https://example.com/vector-db-concepts"
    },
    {
        "id": "doc-004",
        "text": "You can filter Pinecone search results using metadata such as category or difficulty.",
        "category": "faq",
        "tag": "metadata",
        "difficulty": "beginner",
        "url": "https://example.com/pinecone-metadata"
    },
    {
        "id": "doc-005",
        "text": "In Retrieval-Augmented Generation, a vector database like Pinecone stores document chunks.",
        "category": "blog",
        "tag": "rag",
        "difficulty": "intermediate",
        "url": "https://example.com/rag-pinecone"
    }
]


In [ ]:
pc = Pinecone(api_key="pcsk_6vwBK4_GtDM115naFbU1jsSWbD3JwaURZyiaTGKz81VrEaRF3x5DVPgzzAv6zMwHUJvn8R")

In [ ]:
pc

In [ ]:
INDEX_NAME = "pinecone-demo"

In [ ]:
index = pc.Index(INDEX_NAME)

In [ ]:

import requests
import numpy as np

def generate_embeddings(text):
    url = "https://api.euron.one/api/v1/euri/embeddings"
    headers = {
        "Content-Type": "application/json",
        "Authorization": "Bearer euri-f3a8bba1b99c7dff1d1fdddf69634c20b613941037ad64b039567262f062be7f"
    }
    payload = {
        "input": text,
        "model": "text-embedding-3-small"
    }

    response = requests.post(url, headers=headers, json=payload)
    data = response.json()

    embedding = np.array(data['data'][0]['embedding'])

    return embedding


In [ ]:
embeddings = [generate_embeddings(i['text']) for i in documents]
embeddings

[array([-0.00134443,  0.00099503,  0.0258576 , ...,  0.01031686,
        -0.00442852, -0.00440889]),
 array([ 0.02902028,  0.02793078,  0.04518942, ..., -0.01395301,
         0.00476656,  0.01302446]),
 array([-0.02906779,  0.02355646,  0.01056707, ...,  0.02751217,
         0.00487519,  0.00448906]),
 array([ 0.02289019, -0.01053026,  0.05368768, ..., -0.0068709 ,
         0.02045915, -0.01082454]),
 array([ 0.01343644,  0.02367981,  0.04485626, ..., -0.000831  ,
         0.04613349,  0.0182005 ])]

In [ ]:
len(embeddings)

5

In [ ]:
vectors = []

for doc in documents:
    embedding = generate_embeddings(doc["text"])
    vectors.append(
        (
            doc["id"],
            embedding,
            {
                "text": doc["text"],
                "category": doc["category"],
                "tag": doc["tag"],
                "difficulty": doc["difficulty"],
                "url": doc["url"]
            }
        )
    )

In [ ]:
vectors

[('doc-001',
  array([-0.00134443,  0.00099503,  0.0258576 , ...,  0.01031686,
         -0.00442852, -0.00440889]),
  {'text': 'Pinecone is a fully managed vector database for search and recommendation.',
   'category': 'documentation',
   'tag': 'pinecone',
   'difficulty': 'beginner',
   'url': 'https://example.com/pinecone-intro'}),
 ('doc-002',
  array([ 0.02902028,  0.02793078,  0.04518942, ..., -0.01395301,
          0.00476656,  0.01302446]),
  {'text': 'To use Pinecone with Python, you create an index and upsert vectors with metadata.',
   'category': 'documentation',
   'tag': 'python',
   'difficulty': 'beginner',
   'url': 'https://example.com/pinecone-python'}),
 ('doc-003',
  array([-0.02906779,  0.02355646,  0.01056707, ...,  0.02751217,
          0.00487519,  0.00448906]),
  {'text': 'Vector databases store embeddings that capture semantic meaning for semantic search.',
   'category': 'blog',
   'tag': 'vector-db',
   'difficulty': 'intermediate',
   'url': 'https://exam

In [ ]:
index.upsert(vectors=vectors)

UpsertResponse(upserted_count=5, _response_info={'raw_headers': {'date': 'Mon, 23 Feb 2026 10:07:19 GMT', 'content-type': 'application/json', 'content-length': '19', 'connection': 'keep-alive', 'x-pinecone-request-lsn': '2', 'x-pinecone-request-logical-size': '31805', 'x-pinecone-request-latency-ms': '510', 'x-envoy-upstream-service-time': '253', 'x-pinecone-response-duration-ms': '512', 'grpc-status': '0', 'server': 'envoy'}})

In [ ]:
query="what is pinecone"


In [ ]:
query_embed  = generate_embeddings(query).tolist()

In [ ]:
index.query(vector=query_embed, top_k=2, include_metadata=True)

QueryResponse(matches=[{'id': 'doc-001',
 'metadata': {'category': 'documentation',
              'difficulty': 'beginner',
              'tag': 'pinecone',
              'text': 'Pinecone is a fully managed vector database for search '
                      'and recommendation.',
              'url': 'https://example.com/pinecone-intro'},
 'score': 0.613375723,
 'values': []}, {'id': 'doc-002',
 'metadata': {'category': 'documentation',
              'difficulty': 'beginner',
              'tag': 'python',
              'text': 'To use Pinecone with Python, you create an index and '
                      'upsert vectors with metadata.',
              'url': 'https://example.com/pinecone-python'},
 'score': 0.508770943,
 'values': []}], namespace='', usage={'read_units': 1}, _response_info={'raw_headers': {'date': 'Mon, 23 Feb 2026 10:08:35 GMT', 'content-type': 'application/json', 'content-length': '586', 'connection': 'keep-alive', 'x-pinecone-max-indexed-lsn': '2', 'x-pinecone-reque