In [30]:
!pip install chromadb

In [31]:
pip show chromadb

Name: chromadb
Version: 1.5.1
Summary: Chroma.
Home-page: https://github.com/chroma-core/chroma
Author: 
Author-email: Jeff Huber <jeff@trychroma.com>, Anton Troynikov <anton@trychroma.com>
License: 
Location: /usr/local/lib/python3.12/dist-packages
Requires: bcrypt, build, grpcio, httpx, importlib-resources, jsonschema, kubernetes, mmh3, numpy, onnxruntime, opentelemetry-api, opentelemetry-exporter-otlp-proto-grpc, opentelemetry-sdk, orjson, overrides, posthog, pybase64, pydantic, pypika, pyyaml, rich, tenacity, tokenizers, tqdm, typer, typing-extensions, uvicorn
Required-by: 


https://www.trychroma.com/

In [32]:
import chromadb
client=chromadb.Client()

In [33]:
data = [
"Born on November 5, 1988, in Delhi, he grew up playing cricket in local academies before rising to international fame.",
"One of the most consistent batsmen in modern cricket, he is known for his aggressive style and exceptional chasing ability.",
"He made his One Day International debut for India in 2008 against Sri Lanka.",
"From 2014 to 2022, he led the Indian Test team and achieved significant overseas victories as captain.",
"His ability to perform under pressure has earned him the reputation of being one of the best finishers in ODI cricket.",
"Across all international formats, he has scored more than 25,000 runs.",
"In the Indian Premier League, he has been a key player for Royal Challengers Bangalore.",
"A strong advocate of fitness, he transformed the fitness culture within the Indian cricket team.",
"He has received prestigious awards including the Rajiv Gandhi Khel Ratna for his contributions to Indian sports.",
"Multiple centuries in ICC tournaments highlight his dominance on the global stage.",
"After the 2021 T20 World Cup, he stepped down as the captain of India's T20 team.",
"His memorable 82 not out against Pakistan in the 2022 T20 World Cup is considered one of his finest innings.",
"Off the field, he is married to Bollywood actress Anushka Sharma and is known for maintaining a disciplined lifestyle.",
"He has consistently ranked among the top batsmen in ICC rankings across formats.",
"Over the years, he has built a massive global fan following and strong personal brand presence.",
"His leadership period saw India become one of the most competitive Test sides in the world.",
"Known for his intense passion on the field, he brings energy and aggression to every match.",
"Several records in ODI cricket were broken by him, including being the fastest to reach multiple run milestones.",
"He has been one of the highest run-scorers in multiple IPL seasons.",
"His dedication to training and mental strength has been widely praised by former cricketers."
]

In [34]:

import requests
import numpy as np

def generate_embeddings(text):
    url = "https://api.euron.one/api/v1/euri/embeddings"
    headers = {
        "Content-Type": "application/json",
        "Authorization": "Bearer euri-f3a8bba1b99c7dff1d1fdddf69634c20b613941037ad64b039567262f062be7f"
    }
    payload = {
        "input": text,
        "model": "text-embedding-3-small"
    }

    response = requests.post(url, headers=headers, json=payload)
    data = response.json()

    embedding = np.array(data['data'][0]['embedding'])

    return embedding



In [35]:
embeddings=[generate_embeddings(i) for i in data]
embeddings

[array([-0.00873762,  0.01092691,  0.01780754, ..., -0.01467998,
         0.04222205, -0.01475817]),
 array([ 0.05499334,  0.00919583,  0.05994319, ..., -0.04057519,
        -0.0228874 ,  0.01160832]),
 array([-0.02226261, -0.05243558,  0.03383446, ..., -0.00966279,
        -0.00643207, -0.02590451]),
 array([-0.01783084, -0.03134215,  0.07255166, ..., -0.00981617,
         0.00969334, -0.00709856]),
 array([ 0.0349274 ,  0.02744615,  0.05060453, ..., -0.0203892 ,
         0.00862577, -0.00958047]),
 array([-0.00379052,  0.00741838,  0.07840129, ..., -0.0136052 ,
         0.01344254, -0.01640525]),
 array([-0.00094792, -0.00722526,  0.07077807, ...,  0.01052718,
         0.01216498, -0.00710414]),
 array([ 0.00962567,  0.02558803,  0.00842564, ..., -0.00494935,
         0.02153712,  0.00375249]),
 array([ 0.04866834, -0.00939771,  0.01220744, ..., -0.00392202,
         0.05928174,  0.00091556]),
 array([ 0.00527587, -0.02386252,  0.07097445, ..., -0.02062526,
         0.00678108,  0.00

In [36]:
len(embeddings)

20

In [38]:
collection=client.create_collection(name="viratkohli")

InternalError: Collection [viratkohli] already exists

In [39]:
collection.add(
    documents=data,
    embeddings=embeddings,
    ids=[str(i) for i in range(len(data))]
)

In [40]:
collection.count()

20

In [41]:
collection.get()

{'ids': ['0',
  '1',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
  '10',
  '11',
  '12',
  '13',
  '14',
  '15',
  '16',
  '17',
  '18',
  '19'],
 'embeddings': None,
 'documents': ['Born on November 5, 1988, in Delhi, he grew up playing cricket in local academies before rising to international fame.',
  'One of the most consistent batsmen in modern cricket, he is known for his aggressive style and exceptional chasing ability.',
  'He made his One Day International debut for India in 2008 against Sri Lanka.',
  'From 2014 to 2022, he led the Indian Test team and achieved significant overseas victories as captain.',
  'His ability to perform under pressure has earned him the reputation of being one of the best finishers in ODI cricket.',
  'Across all international formats, he has scored more than 25,000 runs.',
  'In the Indian Premier League, he has been a key player for Royal Challengers Bangalore.',
  'A strong advocate of fitness, he transformed the fitness culture with

In [42]:
query="who is virat kholi wife"

In [43]:
query_embed= generate_embeddings(query).tolist()
query_embed

[0.028065242,
 0.014681187,
 -0.007771006,
 0.018584378,
 -0.04910238,
 0.0075292676,
 0.07131873,
 -0.0016066761,
 -0.0061024213,
 -0.03238116,
 0.041979942,
 -0.0016641627,
 -0.06235672,
 -0.027593557,
 0.046508115,
 0.0141033735,
 0.018301368,
 -0.026650187,
 -0.016296707,
 0.0230418,
 0.029291622,
 0.040399797,
 0.010890021,
 -0.023784703,
 0.0191504,
 0.014657603,
 -0.037098005,
 -0.020388572,
 0.0278294,
 -0.02594266,
 0.020081976,
 -0.022275312,
 0.032475494,
 -0.024197426,
 -0.00057965633,
 0.020494701,
 -0.011055111,
 -0.04714489,
 0.0060257725,
 0.035942376,
 -0.0016744807,
 -0.06669622,
 0.009598784,
 0.05688518,
 0.05499844,
 0.041720513,
 -0.013643481,
 0.02248757,
 0.006184966,
 0.010624698,
 -0.0028581147,
 -0.0025072992,
 0.009268605,
 0.085799456,
 -0.0019103232,
 -0.006697923,
 0.012334555,
 0.07867701,
 0.04799392,
 0.020659791,
 -0.026225671,
 -0.015836814,
 -0.013384054,
 0.0026311164,
 -0.007075271,
 -0.015317962,
 -0.04424403,
 0.022581907,
 -0.0048495084,
 -0.00

In [44]:
collection.query(query_embeddings=[query_embed],n_results=2)

{'ids': [['12', '7']],
 'embeddings': None,
 'documents': [['Off the field, he is married to Bollywood actress Anushka Sharma and is known for maintaining a disciplined lifestyle.',
   'A strong advocate of fitness, he transformed the fitness culture within the Indian cricket team.']],
 'uris': None,
 'included': ['metadatas', 'documents', 'distances'],
 'data': None,
 'metadatas': [[None, None]],
 'distances': [[0.9763229489326477, 1.2878364324569702]]}

In [45]:
#  lets create this collection in our own chorma db account
# first get the api key ck-7Nd5srMt2renpKgAxyiPjW45friETUEe1EgSTymTXeYf
# chroma login --api-key ck-7Nd5srMt2renpKgAxyiPjW45friETUEe1EgSTymTXeYf

client=chromadb.CloudClient(
    api_key='ck-7Nd5srMt2renpKgAxyiPjW45friETUEe1EgSTymTXeYf',
    tenant='644c5fff-a65f-4e80-aacf-42c75d924aa1',
    database="Viratkohilinfo123"
)

In [51]:
cloud_collection = client.create_collection(name="yamuna")

In [52]:
cloud_collection.add(
    documents=data,
    embeddings=embeddings,
    ids=[str(i) for i in range(len(data))]
)

In [53]:
cloud_collection.get()

{'ids': ['0',
  '1',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
  '10',
  '11',
  '12',
  '13',
  '14',
  '15',
  '16',
  '17',
  '18',
  '19'],
 'embeddings': None,
 'metadatas': [None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None],
 'documents': ['Born on November 5, 1988, in Delhi, he grew up playing cricket in local academies before rising to international fame.',
  'One of the most consistent batsmen in modern cricket, he is known for his aggressive style and exceptional chasing ability.',
  'He made his One Day International debut for India in 2008 against Sri Lanka.',
  'From 2014 to 2022, he led the Indian Test team and achieved significant overseas victories as captain.',
  'His ability to perform under pressure has earned him the reputation of being one of the best finishers in ODI cricket.',
  'Across all international formats, he has scored more than 25,000

In [54]:
cloud_query="when virat kohil stopped his t20 carrer"

In [58]:
cloud_query_embed = generate_embeddings(cloud_query).tolist()

In [59]:
cloud_collection.query(query_embeddings=[cloud_query_embed], n_results=2)

{'ids': [['10', '11']],
 'distances': [[0.987129, 1.1881279]],
 'embeddings': None,
 'metadatas': [[None, None]],
 'documents': [["After the 2021 T20 World Cup, he stepped down as the captain of India's T20 team.",
   'His memorable 82 not out against Pakistan in the 2022 T20 World Cup is considered one of his finest innings.']],
 'uris': None,
 'data': None,
 'included': ['metadatas', 'documents', 'distances']}